# Generated by Django 5.1.6 on 2025-02-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('RUN', 'Running'), ('BIK', 'Ciclismo'), ('SWM', 'Natación'), ('TRI', 'Triatlon'), ('GYM', 'Gimnasio')], max_length=3)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('RUN', 'Running'), ('BIK', 'Ciclismo'), ('SWM', 'Natación'), ('TRI', 'Triatlon'), ('GYM', 'Gimnasio')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Mesociclos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
