# Generated by Django 5.1.6 on 2025-02-25 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tma', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
        migrations.AlterModelOptions(
            name='goals',
            options={'verbose_name': 'goal', 'verbose_name_plural': 'goals'},
        ),
    ]
