# Generated by Django 5.1.6 on 2025-03-31 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tma", "0004_alter_events_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Zones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Z1", "Zona 1 Recovery"),
                            ("Z2", "Zona 2 Easy Run"),
                            ("Z3", "Zona 3 Tempo"),
                            ("Z4", "Zona 4 Umbral"),
                            ("Z5a", "Zona 5a VO2max"),
                            ("Z5b", "Zona 5b VO2max"),
                            ("Z5c", "Zona 5c Sprint"),
                        ],
                        max_length=3,
                    ),
                ),
                ("minValue", models.FloatField()),
                ("maxValue", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "zone",
                "verbose_name_plural": "zones",
            },
        ),
        migrations.DeleteModel(
            name="Mesociclos",
        ),
        migrations.AddField(
            model_name="goals",
            name="description",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="goals",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="events",
            name="description",
            field=models.CharField(default="", max_length=255),
        ),
    ]
